// <auto-generated />
using System;
using ExamPrepWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamPrepWeb.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519042420_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("ExamPrepWeb.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId");

                    b.HasIndex(new[] { "Title" }, "IX_Course_Title");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Description = "Профильный уровень.",
                            Price = 5000m,
                            StartDate = new DateTime(2026, 8, 19, 7, 24, 20, 125, DateTimeKind.Local).AddTicks(7336),
                            Subject = "Математика",
                            TeacherName = "Иванов И.И.",
                            Title = "Математика ЕГЭ"
                        },
                        new
                        {
                            CourseId = 2,
                            Description = "Интенсивный курс.",
                            Price = 7500m,
                            StartDate = new DateTime(2026, 9, 2, 7, 24, 20, 125, DateTimeKind.Local).AddTicks(7336),
                            Subject = "Английский",
                            TeacherName = "Петрова А.С.",
                            Title = "Английский язык ЕГЭ"
                        },
                        new
                        {
                            CourseId = 3,
                            Description = "Python & C++.",
                            Price = 6000m,
                            StartDate = new DateTime(2026, 9, 19, 7, 24, 20, 125, DateTimeKind.Local).AddTicks(7336),
                            Subject = "Информатика",
                            TeacherName = "Сидоров В.К.",
                            Title = "Информатика ЕГЭ"
                        });
                });

            modelBuilder.Entity("ExamPrepWeb.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex(new[] { "StudentId", "CourseId" }, "IX_UniqueEnrollment")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("ExamPrepWeb.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.HasIndex(new[] { "Email" }, "IX_UniqueEmail")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ExamPrepWeb.Models.Enrollment", b =>
                {
                    b.HasOne("ExamPrepWeb.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamPrepWeb.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ExamPrepWeb.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("ExamPrepWeb.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
